project:
  type: website
  output-dir: docs

subtitle: "Advent of Code: Worked Solutions"
published-title: "Puzzle Date"
author-title: "Puzzle Source"

website:
  title: "Advent of Code: Worked Solutions"
  navbar: false
  sidebar:
    style: "floating"
    search: false
    collapse-level: 1
    contents:
    - section: "2025"
      contents: 2025/R/*
    - section: "2024"
      contents: 2024/R/*
    - section: "2023"
      contents: 2023/R/*
    - section: "2022"
      contents: 2022/R/*
    - section: "2021"
      contents: 2021/R/*
    - section: "2020"
      contents: 2020/R/*
    - text: "Packages & Functions"
      href: helpers.qmd
  page-navigation: true
  bread-crumbs: false
  repo-url: https://github.com/mimmackk/adventofcode
  repo-actions: source

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    toc-expand: 2
    toc-title: Contents

execute:
  freeze: auto
  message: false
  warning: false
  echo: true
  output: false
  eval: false
